spring:
  profiles:
    active: local
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:test}
    password: ${RABBIT_MQ_PASSWORD:test}

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: info